# values.yaml
nms-hybrid:
    apigw:
        image:
            repository: ausente/nms-apigw
            tag: 2.13.0
        service:
            type: LoadBalancer
    core:
        image:
            repository: ausente/nms-core
            tag: 2.13.0
    dpm:
        image:
            repository: ausente/nms-dpm
            tag: 2.13.0
    ingestion:
        image:
            repository: ausente/nms-ingestion
            tag: 2.13.0
    integrations:
        image:
            repository: ausente/nms-integrations
            tag: 2.13.0
    nmsClickhouse:
        persistence:
            size: 1Ti
global:
    nmsModules:
      nms-acm:
        enabled: true
nms-acm:
    acm:
        image:
            repository: ausente/nms-acm
            tag: 1.8.0
        metrics:
            enabled: true
